# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'WeatherReports' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for WeatherReports
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources', '~> 5.0'
  
  target 'WeatherReportsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
    pod 'RxTest'
  end
  
end
